---
# tasks file for firewall-management
- name: Ensure Firewall is installed and running
  ansible.builtin.yum:
    name: firewalld
    state: present
  become: true

- name: Ensure enabled and started
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
  become: true

- name: Get current open ports
  ansible.builtin.command: firewall-cmd --list-ports
  register: current_ports
  become: true

- name: Set fact for current ports
  ansible.builtin.set_fact:
    current_open_ports: "{{ current_ports.stdout.split() }}"

- name: Open Ports
  ansible.posix.firewalld:
    port: "{{ item.port }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewalld_rules[inventory_hostname] | default([]) }}"
  when: firewalld_rules[inventory_hostname] is defined and firewalld_rules[inventory_hostname] | length > 0

  notify: Check if reload is needed

- name: Close unwanted ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: disabled
    immediate: true
  loop: "{{ current_open_ports }}"
  # when: item not in firewalld_rules[inventory_hostname] | map(attribute='port') | default([])
  when:
    - firewalld_rules[inventory_hostname] is defined
    - item not in firewalld_rules[inventory_hostname] | map(attribute='port') | default([])
  notify: Check if reload is needed


